modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="mc_simple_cheats"
version="1.0.0"
displayName="Simple Ingame Cheats Menu"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Daniil, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mc_simple_cheats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration